/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InventoryManagement;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.*;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author munzhunzheleleGundo
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form Main_Window
     */
    public MainWindow() {
        initComponents();
        
    }
     
        String url = "jdbc:MySQL://localhost:3307/inventorymanagement";
       String user = "root";
       String pass = "";
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        AddDate = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Products = new javax.swing.JTable();
        UploadPic = new javax.swing.JButton();
        Insert = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        Online = new javax.swing.JLabel();
        type = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 680));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Barcode:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 170, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Price :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 120, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Image :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 150, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Add Date :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, -1));

        Id.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Id.setPreferredSize(new java.awt.Dimension(59, 50));
        jPanel1.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 500, 50));

        Name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Name.setPreferredSize(new java.awt.Dimension(59, 50));
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 500, 60));

        AddDate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AddDate.setPreferredSize(new java.awt.Dimension(59, 50));
        jPanel1.add(AddDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 500, 60));

        Price.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Price.setPreferredSize(new java.awt.Dimension(59, 50));
        jPanel1.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 500, 60));

        Products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Add Date"
            }
        ));
        Products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Products);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 600, 660));

        UploadPic.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UploadPic.setText("Add Picture");
        UploadPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadPicActionPerformed(evt);
            }
        });
        jPanel1.add(UploadPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 180, 39));

        Insert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Insert.setText("Insert");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });
        jPanel1.add(Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 200, 30));

        Update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 630, 200, -1));

        Delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 630, 200, -1));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 250));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 250, 250));

        Online.setVisible(false);
        jPanel1.add(Online, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 636, 90, 20));

        type.setVisible(false);
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 636, 100, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
       //METHODS// 
    String path2 = null;
   
    
    void Tables(){
         String id, name, price, addDate;
  
      
        int notFound = 0;

        try (Connection con = DriverManager.getConnection(url, user,pass)) {
            Class.forName("com.mysql.cj.jdbc.Driver");

            // Get values from UI components
         
                // Retrieve and display data
                String query2 = "SELECT id, name, price, addDate,Picture FROM main ORDER BY addDate";
                
                try (PreparedStatement ps = con.prepareStatement(query2); ResultSet rs = ps.executeQuery()) {
                    DefaultTableModel tableData = (DefaultTableModel) Products.getModel();
                    while (rs.next()) {
                        String[] dataTable = {
                            rs.getString("id"),
                            rs.getString("name"),
                            rs.getString("price"),
                            rs.getString("addDate"),
                            
                        };
                        tableData.addRow(dataTable);
                    }
                
                }

                
               
             
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }
    /////////////////////////////////////////////////////////////////END///////////////////////////////////////////////////////////////////////////////////////////////////
    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        // TODO add your handling code here:
        String url, user, pass;
        String id, name,price,addDate;
       
        url = "jdbc:MySQL://localhost:3307/inventorymanagement";
        user = "root";
        pass = "";
        id = Id.getText();
            name = Name.getText();
            price = Price.getText();
            addDate = AddDate.getText();
         String query = "INSERT INTO main (id, name, price, addDate,Picture) VALUES (?, ?, ?, ?, ?)";

        try (Connection con = DriverManager.getConnection(url,user,pass);
            PreparedStatement pstmt = con.prepareStatement(query)) {
            pstmt.setString(1, id);
            pstmt.setString(2, name);
            pstmt.setString(3, price);
            pstmt.setString(4, addDate);
            InputStream is = new FileInputStream(new File(path2));
            pstmt.setBlob(5, is);

           pstmt.execute();
           Id.setText("");
           Name.setText("");
           Price.setText("");
           AddDate.setText("");
           image.setIcon(null);
        } catch (SQLException e) {
            e.printStackTrace();
         
        }
        catch(Exception e){
            System.out.println(" " + e.getMessage());
        }
       Tables();
    }//GEN-LAST:event_InsertActionPerformed

    private void UploadPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadPicActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String path = f.getAbsolutePath();
        try {
            BufferedImage bi = ImageIO.read(new File(path));
            Image img = bi.getScaledInstance(250, 250, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            image.setIcon(icon);
            path2 = path;
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_UploadPicActionPerformed

    private void ProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductsMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Products.getModel();
        int selectedRowIndex = Products.getSelectedRow();
        Id.setText( model.getValueAt(selectedRowIndex, 0).toString());
        Name.setText(model.getValueAt(selectedRowIndex, 1).toString());
        Price.setText(model.getValueAt(selectedRowIndex, 2).toString());
        AddDate.setText(model.getValueAt(selectedRowIndex, 3).toString());
        int notFound = 0;
        try{
            Connection con = DriverManager.getConnection(url,user,pass);
            Statement st = con.createStatement();
            String query = "Select Picture from main where id='"+Id.getText()+"'";
            ResultSet rs = st.executeQuery(query);
            if(rs.next()){
                Blob img = rs.getBlob("Picture");
                String path ="C:\\Com1321\\Inventory Management\\Pictures\\img.jpg";
                byte [] Byte = img.getBytes(1, (int)img.length());
                FileOutputStream fos = new FileOutputStream(path);
                fos.write(Byte);
                ImageIcon icon = new ImageIcon(Byte);
                image.setIcon(icon);
            }
        }
        catch(Exception e){
            System.out.println("" + e.getMessage());
        }
        //image.setIcon(model.getValueAt(selectedRowIndex, 4).toString());
       
    }//GEN-LAST:event_ProductsMouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here
    DefaultTableModel model = (DefaultTableModel) Products.getModel();
    int selectedRowIndex = Products.getSelectedRow();
    String id = model.getValueAt(selectedRowIndex, 0).toString();
       String  name,price,addDate; 
       try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url,user,pass);
            Statement st = con.createStatement();
            String query ;
            query ="DELETE FROM main where id ='"+id+"' ";
            st.executeUpdate(query);
            
        }
       catch(Exception e){
           System.out.println("" + e.getMessage());
       }
    }//GEN-LAST:event_DeleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
          try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url,user,pass);
            Statement st = con.createStatement();
            String query ;
            query ="UPDATE main set id = '"+Id.getText()+"',name ='"+Name.getText()+"',Price = '"+Price.getText()+"' where  id ='"+Id.getText()+"' ";
            st.executeUpdate(query);
            Tables();
            
        }
       catch(Exception e){
           System.out.println("" + e.getMessage());
       }
    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddDate;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Id;
    private javax.swing.JButton Insert;
    private javax.swing.JTextField Name;
    public static javax.swing.JLabel Online;
    private javax.swing.JTextField Price;
    private javax.swing.JTable Products;
    private javax.swing.JButton Update;
    private javax.swing.JButton UploadPic;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
