/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InventoryManagement;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.JOptionPane;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author munzheleleGundo
 */
public class Signin extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public Signin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        WorkId = new javax.swing.JTextField();
        PinCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Cashier = new javax.swing.JRadioButton();
        Manager = new javax.swing.JRadioButton();
        Signin = new javax.swing.JButton();
        SignUp = new javax.swing.JButton();
        Help = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Sign-in");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.white, java.awt.Color.gray));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WorkId.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        WorkId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkIdActionPerformed(evt);
            }
        });
        jPanel2.add(WorkId, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 171, 350, 38));

        PinCode.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel2.add(PinCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 270, 350, 38));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel2.setText("Pin Code");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel3.setText("Work ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        Cashier.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Cashier.setText("Cashier");
        Cashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashierActionPerformed(evt);
            }
        });
        jPanel2.add(Cashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        Manager.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Manager.setText("Manager");
        Manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerActionPerformed(evt);
            }
        });
        jPanel2.add(Manager, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        Signin.setBackground(new java.awt.Color(0, 153, 204));
        Signin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Signin.setForeground(new java.awt.Color(255, 255, 255));
        Signin.setText("Sign-In");
        Signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigninActionPerformed(evt);
            }
        });
        jPanel2.add(Signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        SignUp.setBackground(new java.awt.Color(0, 153, 204));
        SignUp.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        SignUp.setForeground(new java.awt.Color(255, 255, 255));
        SignUp.setText("Sign-up");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        jPanel2.add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 760, 480));

        Help.setBackground(new java.awt.Color(102, 255, 102));
        Help.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Help.setText("Help?");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });
        jPanel1.add(Help, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void WorkIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WorkIdActionPerformed

    private void SigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigninActionPerformed
        // TODO add your handling code here:
         MainWindow main = new MainWindow();
        String Workid = WorkId.getText(), Pincode = PinCode.getText(),query ;
        String url,pass,user;
        String dbPin = null ;
        url = "jdbc:MySQL://localhost:3307/inventorymanagement";
        pass="";
        user="root";
        int notFound = 0;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url,user,pass);
            Statement st = con.createStatement();
            if(Cashier.isSelected()){
            query = "SELECT* FROM Cashier where workid = '"+Workid+"'";
             ResultSet rs = st.executeQuery(query);
            while(rs.next() ){
                dbPin = rs.getString("pincode");
                notFound = 1;
            }
            if(notFound ==1 && dbPin.equals(Pincode)){
                main.type.setText(Cashier.getText());
                 main.Online.setText(WorkId.getText());
                main.show();
                this.dispose();
            }
             else{
                    JOptionPane.showMessageDialog(null,"Cashier is not Registered");
                }
            }
            else if(Manager.isSelected()){
                query ="SELECT * FROM manager where workid = '"+Workid+"'";
                ResultSet rs = st.executeQuery(query);
                while(rs.next()){
                  dbPin = rs.getString("pincode");
                notFound =1;
                }
                if(notFound ==1 && Pincode.equals(dbPin)){
               String option = JOptionPane.showInputDialog("ENTER 1 TO LOGIN AS A CASHIER\n ENTER 2 TO MANAGE CASHIERS");
                    if(option.equalsIgnoreCase("1")){
                    main.type.setText(Manager.getText());
                    main.Online.setText(WorkId.getText());
                    main.show();
                    this.dispose();
                
                    }
                    else if(option.equals("2")){
                        //Block of code
                        CashierManage CM = new CashierManage();
                        CM.Main();
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Manager is not Registered");
                }
                
            }
            else{
                JOptionPane.showMessageDialog(null,"Please select whether you are a Cashier or Manager");
            }
        }
        catch(Exception e){
            System.out.println("" +e.getMessage());
            JOptionPane.showMessageDialog(null,"System might be offline");
            
        }
    }//GEN-LAST:event_SigninActionPerformed

    private void ManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerActionPerformed
        // TODO add your handling code here:
        Cashier.setSelected(false);
    }//GEN-LAST:event_ManagerActionPerformed

    private void CashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashierActionPerformed
        // TODO add your handling code here:
        Manager.setSelected(false);
    }//GEN-LAST:event_CashierActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Developers and Designers'contact"
                + "\n"
                + "Munzhelele Gundo"
                + "\n"
                + "Call : +27 71 074 0278"
                + "\n"
                + "     : +27 82 715 1964"
                + "\n"
                + "LinkedIn :Gundo Munzhelele"
                + "\n"
                + "IG       :Gundo Black-Fire Munzhelele"
                + "\n"
                + "Israel Munyai"
                + "\n"
                + "Call : +27 71 081 4288"
                + "\n"
                + "LinkedIn : Israel Munyai"
                + "\n"
                + "IG       :ISY YOUNG ACE"
                + "\n"
                + "Nematswerani Rotondwa"
                + "Call : +27 71 439 7833"
                + "\n"
                + "IG       : Kelvin_nems");
    }//GEN-LAST:event_HelpActionPerformed

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        // TODO add your handling code here:
        Signup sign = new Signup();
        sign.show();
        this.dispose();
    }//GEN-LAST:event_SignUpActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cashier;
    private javax.swing.JButton Help;
    private javax.swing.JRadioButton Manager;
    private javax.swing.JTextField PinCode;
    private javax.swing.JButton SignUp;
    private javax.swing.JButton Signin;
    private javax.swing.JTextField WorkId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
